In [1]:
import numpy as np

In [2]:
l=[1,2,3,4,5]

In [3]:
ar = np.array(l)

In [4]:
ar

array([1, 2, 3, 4, 5])

In [5]:
type(ar)

numpy.ndarray

In [6]:
np.array(([1,2,],[3,4]))

array([[1, 2],
       [3, 4]])

In [7]:
np.asarray(l)

array([1, 2, 3, 4, 5])

In [8]:
a = [2,4,5]

In [9]:
a

[2, 4, 5]

In [10]:
np.asanyarray(a)

array([2, 4, 5])

In [11]:
b = np.matrix(l)

In [12]:
b

matrix([[1, 2, 3, 4, 5]])

In [13]:
np.asanyarray(b)

matrix([[1, 2, 3, 4, 5]])

In [14]:
a = np.array(l)

In [15]:
a

array([1, 2, 3, 4, 5])

In [16]:
c = a

In [17]:
c

array([1, 2, 3, 4, 5])

In [18]:
a

array([1, 2, 3, 4, 5])

In [19]:
c[0]=100

In [20]:
d = np.copy(a)

In [21]:
d

array([100,   2,   3,   4,   5])

In [22]:
np.fromfunction(lambda i,j :i==j,(3,3))

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [23]:
np.fromfunction(lambda i,j :i*j,(3,3))

array([[0., 0., 0.],
       [0., 1., 2.],
       [0., 2., 4.]])

In [24]:
iterable = (i*i for i in range(5))

In [25]:
np.fromiter(iterable,float)

array([ 0.,  1.,  4.,  9., 16.])

In [26]:
np.fromiter(iterable,float)

array([], dtype=float64)

In [27]:
ar = np.array(l)

In [28]:
ar

array([1, 2, 3, 4, 5])

In [29]:
ar.ndim

1

In [30]:
ar2 = np.array([[1,2,3,4],[2,3,4,5]])

In [31]:
ar2

array([[1, 2, 3, 4],
       [2, 3, 4, 5]])

In [32]:
ar2.ndim

2

In [33]:
ar.size

5

In [34]:
ar2.size

8

In [35]:
ar2.dtype

dtype('int64')

In [36]:
list(range(5))

[0, 1, 2, 3, 4]

In [37]:
np.arange(2.3,5.6)

array([2.3, 3.3, 4.3, 5.3])

In [38]:
np.linspace(1,5,10)

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [39]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [41]:
np.empty((3,6))

array([[0., 0., 0., 1., 1., 1.],
       [2., 2., 2., 0., 1., 2.],
       [0., 1., 2., 0., 1., 2.]])

In [44]:
arr = np.random.rand(3,4)

In [45]:
import pandas as pd

In [46]:
pd.DataFrame(arr)

0         1         2         3
0  0.680168  0.346859  0.339412  0.031652
1  0.814168  0.863825  0.267771  0.406747
2  0.372303  0.848850  0.261143  0.436667

In [47]:
np.random.rand(3,4)

array([[0.34076371, 0.61073824, 0.25936529, 0.11910898],
       [0.90855131, 0.70296031, 0.79674172, 0.17648925],
       [0.5247187 , 0.27302994, 0.83244009, 0.50202819]])

In [48]:
pd.DataFrame(np.random.randint(1,110,(300,400))).to_csv('test.csv')

In [49]:
arr = np.random.rand(3,4)

In [50]:
arr

array([[0.45115614, 0.88995509, 0.61158791, 0.33083099],
       [0.2571147 , 0.85506663, 0.45814267, 0.10305928],
       [0.8260268 , 0.7146957 , 0.46798694, 0.68484327]])

In [51]:
arr.reshape(6,-1)

array([[0.45115614, 0.88995509],
       [0.61158791, 0.33083099],
       [0.2571147 , 0.85506663],
       [0.45814267, 0.10305928],
       [0.8260268 , 0.7146957 ],
       [0.46798694, 0.68484327]])